### ISSUE TITLE
[Fix] 달력 페이지 공간 수정

### ISSUE THREAD

**Issue by rkwhrcjsaud** [WeAreSide/DNFCal#21]
## ✏️ Description

달력의 길이가 유동적임에 따라 달력 페이지 구조 수정
배경이 적용됨에 따라 그리드 크기확인용 색 대신 투명화적용

## ✅ Todo
- [x] 달력 페이지 위젯 공간 수정
- [x] 달력 페이지 배경 수정
- [x] 등록된 캐릭터 페이지 배경 수정
