### ISSUE TITLE
[Fix] 달력 페이지, 등록된 캐릭터 페이지 디자인 수정

### ISSUE THREAD

**Issue by rkwhrcjsaud** [WeAreSide/DNFCal#28]
## ✏️ Description

달력 페이지 모험단 정보 구조 수정
등록된 캐릭터 페이지 위젯 구조 수정
등록된 캐릭터 페이지 더미 캐릭터 이미지로 변경

## ✅ Todo
- [x] 달력 페이지 모험단 정보 구조 수정
- [x] 등록된 캐릭터 페이지 위젯 구조 수정
- [x] 등록된 캐릭터 페이지 더미 캐릭터 이미지로 변경
