### ISSUE TITLE
[Refactor] 달력 페이지, 등록된 캐릭터 페이지 Refactoring

### ISSUE THREAD

**Issue by rkwhrcjsaud** [WeAreSide/DNFCal#31]
## ✏️ Description

달력 페이지, 등록된 캐릭터 페이지의 위젯분리 및 Refactoring
달력 페이지 padding 재수정
CustomColor의 common, uncommon swap

## ✅ Todo
- [x] 자주 사용되는 Text스타일 위젯화
- [x] Widget 파일 분리
- [x] 긴 Style 분리
- [x] 달력 padding 재수정 
- [x] CustomColor 수정 및 전체 적용
