### ISSUE TITLE
[Fix] 서버 선택 한글로 변경, 검색결과 없을시 텍스트 표시, 네트워크 이미지 공간 잡기

### ISSUE THREAD

**Issue by dayjack** [WeAreSide/DNFCal#40]
## ✏️ Description

서버 선택 한글로 변경, 검색결과 없을시 텍스트 표시, 네트워크 이미지 공간 잡기

## ✅ Todo
- [x] 서버 선택 한글로 변경
- [x] 검색결과 없을시 텍스트 표시
- [x] 네트워크 이미지 공간 잡기
