### ISSUE TITLE
[Feat] 달력 페이지 DB 연동

### ISSUE THREAD

**Issue by rkwhrcjsaud** [WeAreSide/DNFCal#50]
## ✏️ Description

달력 페이지의 정보를 DB와 연동하여 이전 기록과 현재 날짜에 갱신을 진행한다.

## ✅ Todo
- [x] 등록된 캐릭터 페이지에 실제 모험단 이름 연동
- [x] 등록된 캐릭터 페이지에서 캐릭터 삭제 후 isEdit모드 false로 변경
- [x] 달력 페이지에 실제 모험단 정보 연동
- [x] 달력 페이지에 사용될 DB class 추가
- [x] 달력 페이지의 Refresh버튼을 누르면 등록된 캐릭터들의 정보를 갱신한 뒤 총합템레벨의 평균을 기록
- [x] 기록된 날짜도 DB에 저장하여 불러오는 기능을 추가
