### ISSUE TITLE
[Asset] 명성 이미지, 앱 아이콘 추가 및 적용

### ISSUE THREAD

**Issue by rkwhrcjsaud** [WeAreSide/DNFCal#52]
## ✏️ Description

명성 이미지, 앱 아이콘 추가

## ✅ Todo
- [x] 명성 이미지 추가, 적용
- [x] 앱 아이콘 추가, 적용
- [x] 등록된 캐릭터 페이지 아이템 레벨 색 수정
